// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-G2o0ZtFquqwqWdJacIqGnWS_m0SV16E',
    appId: '1:85053124001:web:7bae77e47147fb996aafe0',
    messagingSenderId: '85053124001',
    projectId: 'picas-y-fijas',
    authDomain: 'picas-y-fijas.firebaseapp.com',
    storageBucket: 'picas-y-fijas.appspot.com',
    measurementId: 'G-CK6XYN2SD0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtDpEvvkt523_rQ1l3H-E0unY0ApRFEqU',
    appId: '1:85053124001:android:546204af56f74e1f6aafe0',
    messagingSenderId: '85053124001',
    projectId: 'picas-y-fijas',
    storageBucket: 'picas-y-fijas.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMXOcxGToUk8wpmc1k8TOXmUD0WMDikj8',
    appId: '1:85053124001:ios:99d235914a3dc4146aafe0',
    messagingSenderId: '85053124001',
    projectId: 'picas-y-fijas',
    storageBucket: 'picas-y-fijas.appspot.com',
    androidClientId: '85053124001-0hhb5tag22tr28t2413j31pvkldq8vet.apps.googleusercontent.com',
    iosClientId: '85053124001-r3graru8issplr1e8i738s25p00k7hnd.apps.googleusercontent.com',
    iosBundleId: 'com.ivanasdw.bullsncows',
  );
}
